### ISSUE TITLE
@and and @but not supported

### ISSUE THREAD

**Issue by Lucretia** [briot/gnatbdd#3]
Please add these to complete the project, gnatbdd-codegen.adb: 51

```
   Cst_Comment_Re : constant Pattern_Matcher :=
     Compile ("--\s*@(given|then|when|and|but)\s+");
```

**Comment by briot** [comment]
I haven't worked or used this project for years now, so I forgot the details, but I think this proposal does not make sense.
If I remember right, the idea is that in your your code you specify what procedures can be used for the initial setup ("given"), which can be used to perform actions in the test ("when"), and which can be used for actually testing ("then").

In your features file (the text file), you can then use "when", "and",... as you will. But the code annotation is always using "when".

**Comment by Lucretia** [comment]
You have provided Cst_And and Cst_But but didn't include them. It makes sense to do this as there are people using them, the Cucumber specs also provide them. The book I am using, uses them, without them following this book's first chapter is a non-starter.

**Comment by briot** [comment]
> You have provided Cst_And and Cst_But but didn't include them. It makes sense to do this as there are people using them, the Cucumber specs also provide them. The book I am using, uses them, without them following this book's first chapter is a non-starter.


Could you provide an example where they are needed ? That might help refresh my memory, too.

**Comment by Lucretia** [comment]
Literally [this project](https://github.com/Lucretia/raytracer_challenge/blob/main/src/features/tuples.feature)

**Comment by briot** [comment]
> Literally this project


I don’t think it requires @and though.

If you use @then in tuples-steps.ads, things will work as expected.

After all, you might be using

  when a.y = 2
    and a.x = 1

as well as

  when a.x = 1
   and a.y = 2
 
And you would not want to have to annotate both with @and and @when.
Which is why the only annotation is @when

**Comment by Lucretia** [comment]
These are pasted from the book. I'm trying to follow the book so it all makes sense. Yes they do essentially the same thing, but the markup makes it clearer.

**Comment by Lucretia** [comment]
Your code doesn't even do anything with @and, it completely ignores it.
